# Generated by Django 4.2.3 on 2023-07-29 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert',
            new_name='Advertisement',
        ),
    ]
