# Generated by Django 4.2.3 on 2023-08-03 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0003_remove_advertisement_ooo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisement',
        ),
    ]
