# Generated by Django 4.2.3 on 2023-08-03 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0004_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
