# Generated by Django 4.2.3 on 2023-08-06 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0005_alter_advertisement_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Advertisemen',
        ),
    ]
