# Generated by Django 4.2.3 on 2023-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0011_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
