# Generated by Django 4.2.3 on 2023-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0012_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
