# Generated by Django 4.2.3 on 2023-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0013_alter_advertisement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
