# Generated by Django 4.2.3 on 2023-08-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_adv', '0015_alter_advertisement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, help_text='не обязательно', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, help_text='не обязательно', null=True, upload_to='media/',
                                    verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='не обязательно', max_digits=100,
                                      null=True, verbose_name='Цена'),
        ),
    ]
